sudo: required
language: node_js
node_js:
  - 13.0.1
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
install:
  # install deps
  - npm install
script:
  - npm build
  - docker build -t macaicedo/back .
  - docker tag macaicedo/back registry.heroku.com/$HEROKU_APP_NAME/web
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push macaicedo/back;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master