sudo: required
language: node_js
node_js:
  - 13.0.1
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - npm install
script:
  - npm build
  - docker-machine ip
  - docker build -t macaicedo/back .
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push macaicedo/back;
  on:
    branch: master