version: "3"
services:
  web:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27015:27017"